id = "codebook"
name = "Codebook Spell Checker"
version = "0.2.12"
description = "📒 A fast, code aware spell checker."
authors = ["Bo"]
license = "MIT"
schema_version = 1
repository = "https://github.com/cloned-doy/codebook"

[language_servers.codebook]
name = "codebook"
languages = [
  "AsciiDoc",
  "Astro",
  "C",
  "C++",
  "CSS",
  "CSharp",
  "Dart",
  "Elixir",
  "Erlang",
  "Go",
  "Haskell",
  "HTML",
  "Java",
  "JavaScript",
  "JavaScript React",
  "LaTeX",
  "Lua",
  "Markdown",
  "MDX",
  "OCaml",
  "Odin",
  "PHP",
  "Plain Text",
  "Python",
  "R",
  "Ruby",
  "Rust",
  "Shell Script",
  "Swift",
  "Svelte",
  "TOML",
  "TSX",
  "TypeScript",
  "TypeScript React",
  "Typst",
  "VHDL",
  "Vue.js",
  "YAML",
  "Zig",
]
